plugins {
    id 'com.iamkaf.multiloader.common'
}

def nightConfigVersion = requiredProp(project, 'nightconfig_version')

if (project.parent?.name == 'common') {
    def minecraftVersion = requiredProp(project, 'project.minecraft')
    def modName = requiredProp(project, 'mod.name')

    tasks.named('processResources').configure {
        inputs.property 'minecraft_version', minecraftVersion
        inputs.property 'mod_name', modName
        filesMatching('pack.mcmeta') {
            expand([
                minecraft_version: minecraftVersion,
                mod_name: modName,
            ])
        }
    }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'
    implementation "com.electronwill.night-config:core:${nightConfigVersion}"
    implementation "com.electronwill.night-config:toml:${nightConfigVersion}"
}
